/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI Monitoring
 * Set of APIs to monitor machines (CPU usage)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * An order for a pets from the pet store
 * @export
 * @interface CPULoad
 */
export interface CPULoad {
    /**
     * 
     * @type {string}
     * @memberof CPULoad
     */
    time: string;
    /**
     * 
     * @type {number}
     * @memberof CPULoad
     */
    average: number;
}

/**
 * CpuApi - axios parameter creator
 * @export
 */
export const CpuApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Return the CPU load (actualized every 10s)
         * @summary CPU Load Information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLoad: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/cpu/load`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CpuApi - functional programming interface
 * @export
 */
export const CpuApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CpuApiAxiosParamCreator(configuration)
    return {
        /**
         * Return the CPU load (actualized every 10s)
         * @summary CPU Load Information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLoad(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CPULoad>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLoad(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CpuApi - factory interface
 * @export
 */
export const CpuApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CpuApiFp(configuration)
    return {
        /**
         * Return the CPU load (actualized every 10s)
         * @summary CPU Load Information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLoad(options?: any): AxiosPromise<CPULoad> {
            return localVarFp.getLoad(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CpuApi - object-oriented interface
 * @export
 * @class CpuApi
 * @extends {BaseAPI}
 */
export class CpuApi extends BaseAPI {
    /**
     * Return the CPU load (actualized every 10s)
     * @summary CPU Load Information
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CpuApi
     */
    public getLoad(options?: any) {
        return CpuApiFp(this.configuration).getLoad(options).then((request) => request(this.axios, this.basePath));
    }
}


